### ISSUE TITLE
Investigate sound effects and music options

### ISSUE THREAD

**Issue by mrcrowley42** [mrcrowley42/godot-project#14]

**Comment by magmmo** [comment]
Need: 
stats low noise
stats increased noise
calm, royalty free, creative commons music

**Comment by magmmo** [comment]
**Current Estimate: 18th July**

**Comment by magmmo** [comment]
@M-Gellel Please provide an update.

**Comment by M-Gellel** [comment]
Currently no progress - Been very busy with other tasks - 9/8/24

**Comment by magmmo** [comment]
https://onemansymphony.bandcamp.com/album/reflective-district-vol-2-free
https://onemansymphony.bandcamp.com/album/reflective-district-free
https://onemansymphony.bandcamp.com/album/a-new-days-hurry-free
https://opengameart.org/
https://freemusicarchive.org/home

**Comment by magmmo** [comment]
Requirements for the week:
1 song by Friday, 23rd August. Song must be calm/chill background music and permit use with the relevant copyright.
Song can be provided as a link or in a folder in the repository. Please assure to update this ticket with a comment when you have chosen a song, along with it's source link & credit.

**Comment by M-Gellel** [comment]
Added ambient audio folder, including 17 audio files

**Comment by M-Gellel** [comment]
Added 4 new audio files - 1 Electrical and 3 Vinyl Sounds

**Comment by magmmo** [comment]
Files have been added to the game and implemented into a background sound system. Closing tickets
