### ISSUE TITLE
Build Foundations For Characters

### ISSUE THREAD

**Issue by LCameron905** [mrcrowley42/godot-project#18]
Get Nodes, classes and scripts ready for implementing the different Creatures.

- creature scenes for each creature to store their individual sprites and needs
- build randomize in egg scene to select random egg sprite and pick which baby creature to use for "play through"
- implement stat class constructor for each creature

**Comment by magmmo** [comment]
**Current Estimate: 25th July**

**Comment by magmmo** [comment]
@LCameron905 Please provide an update.

**Comment by LCameron905** [comment]
will be complete by next Friday (23/09/2024)

**Comment by LCameron905** [comment]
the creature selector has be made and currently selects a creature at random and we need to build a way to use it as a condition for when using the creature class constructor for stats.
