### ISSUE TITLE
Prepare Instructions for Minigames

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#21]
Write up clear, easy English instructions for the minigames. Can be written in Word; we can add it in later when the text is finalised. 

- [x] Scissors Paper Rock
- [x] Tetris
- [x] Memory Match

**Comment by magmmo** [comment]
**Current Estimate: 25th July**

**Comment by Biccaboca** [comment]
Instructions for current mini games are done. The instructions I wrote can be considered a draft if changes need to be made.

**Comment by Biccaboca** [comment]
Estimated time for finishing this task was two weeks (due on the 25/7) but sickness and increased work load from AFP team lead to the task being delayed until the 1/8.

**Comment by magmmo** [comment]
These are great - though in my opinion a little too specific. Try condensing these down to just the rules (and controls if needed, like for Totris). Note that these will be shown after opening the minigame so you don't need to provide instructions on how to access the game. Think about when you open a game on your laptop, how there's a little pause before you start that explains the gist of how to play. :)

**Comment by magmmo** [comment]
Sorry I apparently clicked closed with comment - stupid mouse pad.

**Comment by Biccaboca** [comment]
Currently editing instructions based on feedback.

**Comment by Biccaboca** [comment]
Edited instructions for mini-games edited version added.
