### ISSUE TITLE
Totris

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#22]
Make Totris fully functional as a minigame. Will be considered Closed when game is functioning as intended and has a "game end".

**Comment by magmmo** [comment]
**Current Estimate: 18th July**

**Comment by magmmo** [comment]
❗**Not a bug, but a major flag I found in researching:**
Our Tetris (which shall now be dubbed Totris or Notris, unless you have a name in mind yourself lmao) needs to be "unique". While this is an amazing tetris built from the ground up and I highly recommend you save the code and such in a separate project to preserve it as is, there are some legal implications we have to meet. The game mechanics are not copyrightable, however if the game resembles Tetris too much it can be an issue. This can be resolved through very simple features such as changing the grid dimensions and general design. More advanced things would be changing the goal or adding new features. 
I am happy to provide assistance at looking into this; as we're not monetising, we can get away with a bit more, however it does not protect us from copying and still requires us to make our own spin on things. An example of what appears to be a passable tetris clone is [blockrain.js.](https://aerolab.github.io/blockrain.js/)

[Edit: this is the main Reddit post I was reading, which includes a handy comment by a lawyer who breaks it down.](https://www.reddit.com/r/gamedev/comments/5kkk82/law_concerns_when_creating_a_game_inspired_by/)

**Comment by ghost** [comment]
14th july: completed base Totris game.

On the issue of copyright, "variants" have been added. When first spawned in, a piece has a very low chance to be a variant. Currently only one variant exists: Bonus Points.

Visually, bonus point pieces have a shine that is displayed every 2 seconds, and functionally, they reward 200 extra points for each of its squares that are broken.  Currently 2% chance to spawn when the level is over 0.

If it fits, more variants can be added, but preferably in a different Totris game mode. BUT only if it fits in with the game. Especially right now as the minigames are incredibly unbalanced in terms of individual scale.
