### ISSUE TITLE
Stat Notifications

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#25]
Add function for creature to notify you when it needs something

- [x] Audio queue
- [x] Visual prompt

**Comment by mrcrowley42** [comment]
We currently have hunger, thirst, fun, and regulation as the 4 creature stats, but where exactly does HP fall into this picture?

**Comment by mrcrowley42** [comment]
**Currently blocked.**
We currently have hunger, thirst, fun, and regulation as the 4 creature stats, but there also exists a concept of HP which is currently tied to hunger. Probably a good idea to clear up this confusion and clearly outline the stats.

**Comment by magmmo** [comment]
I love that I can't just reply to comments like I can on Gitlab grrr. Anyway adding this in from our conversation last week:
Stats have been discussed - Health is essentially the Regulation stat. Providing the user looks after the creature (assures they maintain the other stats on a regular basis, logs in regularly, uses the holiday mode when away), Regulation stays up. As the user begins to "neglect" the creature, this begins to go down. We shall discuss the parameters requiring a Regulation drop later down the line when that stat is ironed out.

**Comment by magmmo** [comment]
Didn't check the code so this is purely an assumption from a quick gameplay test, but it appears that the cooldown prevents all notifications from appearing. Meaning if one stat has dropped and providing a notification, if a second stat reaches the low point, it won't provide it's own notification. Will have to set them up on separate timers. 
Otherwise if you're not using cooldowns than yeah only one notification will appear until you press restore stats, and then just the first to reach the low point pops up.

**Comment by mrcrowley42** [comment]
**No longer blocked.**

Thanks for clarifying the stats @magmmo 

> Didn't check the code so this is purely an assumption from a quick gameplay test, but it appears that the cooldown prevents all notifications from appearing. Meaning if one stat has dropped and providing a notification, if a second stat reaches the low point, it won't provide it's own notification. Will have to set them up on separate timers. Otherwise if you're not using cooldowns than yeah only one notification will appear until you press restore stats, and then just the first to reach the low point pops up.

The way I have it currently working is that the game only checks if a stat is low if it's not already on cooldown, so if stat becomes low after a notification has just played it currently won't be checked until the cooldown is over. My aim was to prevent the player from being bombarded by notifications; I can certainly modify this though.
