### ISSUE TITLE
Miniplayer/"Clippy" Mode

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#26]
Mode to change window to miniature, non-intrusive mode to allow for constant presence whilst avoiding taking up screen space. Reminiscent of our old friend Clippy.
Clippy Mode will be equivalent to current "zen mode"; stat bars are absent, however a little visual notification (think bubble?) will appear when a stat is low, and provide audio queue on occasion. These notifications will be created as part of the Stat Notifications ticket and only require being incorporated into Clippy Mode.

**Comment by magmmo** [comment]
Clippy Mode will be equivalent to current "zen mode"; stat bars are absent, however a little visual notification (think bubble?) will appear when a stat is low, and provide audio queue on occasion. These notifications will be created as part of the Stat Notifications ticket and only require being incorporated into Clippy Mode.

**Comment by magmmo** [comment]
**Current Estimate: 18th July.**

**Comment by magmmo** [comment]
❗Clippy mode still retains the same dedicated area as regular mode. This causes the screen to be inaccessible behind where the window would be, but still visible due to the lack of UI.
❗ For some reason, despite the fact the original window can be moved around regardless of screen limits (as in it can be moved off screen), if Clippy Mode is activated, the creature will not move outside of the screen boundary based on the original window size. This can currently be circumvented by placing the window so the creature is in the desired location prior to activating Clippy Mode, however if you move it back into the limits the issue occurs.

**Comment by mrcrowley42** [comment]
-  Fix framerate when application is not in focus.

**Comment by mrcrowley42** [comment]
I'm Scraping try to get transparent areas of window to pass through clicks; it looks like it requires messing with the OS. 
Instead going to try instead to just make game window shrink to a smaller size.
