### ISSUE TITLE
Time of Day

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#29]
Idea: according to time of day, perhaps the background changes - window shows changing time (morning, afternoon, evening, night).

**Comment by ghost** [comment]
Background has upper & lower colours that fade across each other vertically along a gradient & appears stronger near nighttime. Light rays shine from east to west stretching longer at dawn and dusk & fade along a gradient over the day.

All values update in real time (kinda like animal crossing) according to the computers system time. But can be manually set in the debug window.

A "light map" is required for each background to define what is "outside". Red > 0 is considered outside, and red == 0 is not considered outside. The dimensions should be the same as the bg image.

**Comment by magmmo** [comment]
Looking fantastic. The only thing I'd say is maybe down the line might be worth adding a sun/moon to the cycle to make it more obvious? But that's just fluff and absolutely not required if it's too much work.
