### ISSUE TITLE
Dedicated cosmetics menu

### ISSUE THREAD

**Issue by ghost** [mrcrowley42/godot-project#33]
A cosmetics menu to view unlocked (& locked) cosmetics, and equip and dequip them.

**3 sections:**
-  hats
- accessories (like glasses)
- themes  (also backgrounds in themes section?)

**Comment by magmmo** [comment]
Expanding on backgrounds, perhaps it could be as simple as changing the "wallpaper" pattern, and/or adding furniture? Definitely something to discuss and look in to.

**Comment by mrcrowley42** [comment]
Currently waiting for further direction on how the menu will be laid out.

**Comment by mrcrowley42** [comment]
Cosmetics menu is working, additional work required to get the preview feature working.
