### ISSUE TITLE
cosmetic unlock popup/toast

### ISSUE THREAD

**Issue by ghost** [mrcrowley42/godot-project#34]
(IDK IF WE WANT TO ACTUALLY DO THIS)

some kind of pop-up or toast to announce that a new cosmetic was unlocked (and what it is).

if a minigame is running, it should still notify, but not be too obtrusive

**Comment by magmmo** [comment]
This would probably be a great place to incorporate your confetti & the classic Yippee noise, haha. Perhaps for minigames, have to set that it waits till the end of the game to notify? Or create a different, mini version for it. Certainly worth brainstorming.

**Comment by mrcrowley42** [comment]
I've added this notification system to the main branch, but it currently doesn't work for Totris which is a 'full-screen' game. Happy to work this out with @Bryce-VE.
