### ISSUE TITLE
Add life stages

### ISSUE THREAD

**Issue by mrcrowley42** [mrcrowley42/godot-project#43]

**Comment by mrcrowley42** [comment]
An `XP` stat and system has been added along with a `LifeStage` enum, just need a way to transition between life stages (perhaps something like pokemon with it cutting to an evolution animation)

**Comment by ghost** [comment]
> An `XP` stat and system has been added along with a `LifeStage` enum, just need a way to transition between life stages (perhaps something like pokemon with it cutting to an evolution animation)

ya, but it probably shouldn't *automatically* age the creature to an adult. Maybe when the creature has enough `XP` a button should appear somewhere, and when pressed it ages the creature up then.
