### ISSUE TITLE
Add a transition scene when a Creature grows up

### ISSUE THREAD

**Issue by mrcrowley42** [mrcrowley42/godot-project#57]
> An `XP` stat and system has been added along with a `LifeStage` enum, just need a way to transition between life stages (perhaps something like pokemon with it cutting to an evolution animation)
> 
> ya, but it probably shouldn't *automatically* age the creature to an adult. Maybe when the creature has enough `XP` a button should appear somewhere, and when pressed it ages the creature up then. 

 _Originally posted by @Bryce-VE in [#43](https://github.com/mrcrowley42/godot-project/issues/43#issuecomment-2322732389)_

Perhaps we update the Creature class with adults that It can evolve into.

**Comment by ghost** [comment]
@magmmo @mrcrowley42  we should probably discuss this cause i really dont know where we want to go with this scene
