### ISSUE TITLE
Implement "ambience" feature

### ISSUE THREAD

**Issue by magmmo** [mrcrowley42/godot-project#60]
Rather than having music, I think it would be better if we instead had a list of ambient noises that people can toggle for white noise purposes. Things like rain, wind, birds, typing, fireplace crackling, etc. Think ASMR but general background noise.
This also gives us another avenue to unlock cosmetics - perhaps using certain sounds for some time could unlock relevant cosmetics, like rain gets you an umbrella hat, wind a beanie, etc. 
What this needs is a menu where people can toggle individual sounds to create their own unique soundscape. 
Sounds themselves will be supplied through a different ticket.

---

* [x] sound categories & their sound dropdowns added
* [x] current active sound effects are displayed in a green scroll container
* [x] sounds are saved when added, removed, or the volume is changed

**Comment by mrcrowley42** [comment]
FYI I've added a `AmbienceManager` to the main scene as well as adding some of the boiler plate code for it.

**Comment by ghost** [comment]
A thought for the sounds: 
When the main scene is loaded in, we probably want ambience to fade in (as the tracks will eventually be perfect loops).
And when the main scene is closed, we want sound to fade out before switching scenes (similar to how the egg opening scene's music fades out when transitioning to the main scene).
