### ISSUE TITLE
cosmetic buttons toggle

### ISSUE THREAD

**Issue by ghost** [mrcrowley42/godot-project#68]
The cosmetic buttons should be toggled on if that cosmetic is currently equipped. (and off if it is not)

This is to make a better distinction between cosmetics that are equipped and ones that aren't.

The buttons' theme (menu_btn_dark.tres) is already be configured.

**Comment by mrcrowley42** [comment]
I've updated the logic for the buttons and created a new theme specifically for them, they just need to be styled appropriately now.
