### ISSUE TITLE
proper tooltip

### ISSUE THREAD

**Issue by ghost** [mrcrowley42/godot-project#70]
i'm not a fan of godot's built in tooltip, it looks too similar to a browser. And we can do better than that i'm sure. 

* try use built in method first

So I'm gonna *try* make a custom node extending from `Button` as a plugin (idk thats just what the docs say). 
The plan is the custom node will be the same as a `Button` node, but will also let us declare a tooltip string, which direction the tooltip should display from the button, and what theme the tooltip will appear as.

https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#a-custom-node

**Comment by mrcrowley42** [comment]
Looks like there may already be a built-in method to achieve this https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-private-method-make-custom-tooltip

**Comment by ghost** [comment]
> Looks like there may already be a built-in method to achieve this https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-private-method-make-custom-tooltip

i got this working, but it seems the position of the tooltip can't be overridden, which was one of the main reasons I wanted to change it D: 

i'll do something similar to the grow up button but as a new node, called `CustomTooltipButton`. No plugin needed as I didnt realise that if a script extends from a built-in node it acts like a custom node :)
